/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a backup of everything
         * @description One JSON document with everything the user created: rooms (with their logos), user-defined variants and whether each built-in one is active, every game (those in play too) and every bankroll movement. It says the version of its format (`formatVersion`) and the version of the application that made it.
         *
         *     The file comes as an attachment named after the day, e.g. `poker-bankroll-backup-2026-10-02.json`. Restore it with `POST /backup/restore`.
         */
        get: operations["downloadBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a backup, replacing everything
         * @description The body is the file of `GET /backup` itself, up to 32 MB, in any version of the format up to the current one. Restoring **deletes everything the installation holds** (games, bankroll movements, rooms and their logos, user-defined variants) and writes what the file holds; built-in variants are active or not as the file says.
         *
         *     It is all or nothing: with an error in the content of the file nothing changes, and the response (still 200) lists the errors with `restored: false`, each with its place in the document. With `dryRun=true` the file is checked in the same way and nothing changes either: the response says what the file holds and what the installation holds and would lose.
         *
         *     An installation that has data is only replaced with `replace=true`; without it the restore fails with `BACKUP_REPLACE_NOT_CONFIRMED` (409). A file that cannot be read as a whole fails with `BACKUP_FILE_MALFORMED` or `BACKUP_FORMAT_TOO_NEW` (made by a newer version of the application) (400), or `BACKUP_FILE_TOO_LARGE` (413).
         */
        post: operations["restoreBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankroll/evolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poker bankroll per period, for each currency and room
         * @description For each period with movements or games: what was deposited, withdrawn, got as bonuses or adjusted, the net of the games (those in play included) and the bankroll when the period ends. Unlike the cumulative net of `/stats/groups`, the bankroll includes everything before the range (`startingBankroll`), so the last one without dates is the one of `/bankroll/summary`. Currencies and rooms with nothing in the range and no bankroll at its start are left out.
         */
        get: operations["evolution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankroll/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bankroll movements, newest first
         * @description All filters are optional and combined with AND.
         */
        get: operations["list_3"];
        put?: never;
        /**
         * Record a bankroll movement
         * @description Of a room (`roomId`), or of the bankroll as a whole (`currencyCode`, no room).
         */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankroll/movements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a bankroll movement */
        get: operations["get_2"];
        /**
         * Update a bankroll movement
         * @description Replaces every field.
         */
        put: operations["update_3"];
        post?: never;
        /** Delete a bankroll movement */
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankroll/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poker bankroll per currency and room
         * @description bankroll = deposited - withdrawn + adjustments + result, with result = net of the games + bonuses. It is not the balance of the room account: with no movements recorded it is just the result, negative when losing.
         */
        get: operations["summary_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Currencies, game types and modalities, in display order */
        get: operations["catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the finished games as a CSV or Excel file
         * @description Every **finished** game the filters select (those of the games list, combined with AND), not a page of them, oldest first. Games in play are never exported.
         *
         *     `CSV` is the format of the import (`docs/import.md`): importing the file into an empty database records the same games. `XLSX` is made to be read: dates and amounts are typed cells, it adds what was invested and the net of each game, and its headers and values are in the language of `Accept-Language`.
         *
         *     The file comes as an attachment named after its content and the day, e.g. `poker-bankroll-games-2026-10-02.csv`.
         */
        get: operations["exportGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the bankroll movements as a CSV or Excel file
         * @description Every movement the filters select (those of the list of movements, combined with AND), not a page of them, oldest first: date, type, room (empty when it belongs to no room), currency, amount and notes. The amount is signed (a withdrawal is negative), so the amounts of a currency add up to what they did to the bankroll.
         *
         *     `CSV` carries codes; `XLSX` is made to be read: dates and amounts are typed cells and its headers and types are in the language of `Accept-Language`.
         *
         *     The file comes as an attachment named after its content and the day, e.g. `poker-bankroll-movements-2026-10-02.xlsx`.
         */
        get: operations["exportMovements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List games
         * @description All filters are optional and combined with AND.
         */
        get: operations["list_2"];
        put?: never;
        /**
         * Record a game
         * @description With only the required fields the game is recorded as in play; send a result (or `status: FINISHED`) to record it finished.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest names of recorded games
         * @description The names containing the text, most used first, then most recent, then by name. Names that differ only in case or surrounding spaces are one, written as in its most recent game (latest date, then latest id), whose type, modality, buy-in and variant come with it. Games in play count too.
         */
        get: operations["names"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game */
        get: operations["get_1"];
        /**
         * Update a game
         * @description Replaces every field; omitted optional fields take their default.
         */
        put: operations["update_2"];
        post?: never;
        /** Delete a game */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish a game in play
         * @description Sets its result; with no body (or an empty one) nothing was won.
         */
        post: operations["finish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/re-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a re-entry to a tournament or Sit&Go in play
         * @description Adds one entry, paid in cash.
         */
        post: operations["addReEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/rebuys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a rebuy to a cash game in play
         * @description Adds the amount to the buy-in.
         */
        post: operations["addRebuy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import games from a CSV file
         * @description The body is the file itself, in the format of `docs/import.md`: UTF-8, comma separated, a header row and one game per row, up to 5 MB and 50,000 rows. Every game is imported as finished; rooms and variants that do not exist are created.
         *
         *     It is all or nothing: with an error in any row nothing is stored, and the response (still 200) lists the errors with `imported: false`. With `dryRun=true` the file is checked in the same way and nothing is stored either. Importing the same file twice records its games twice.
         *
         *     A file that cannot be read as a whole fails with `IMPORT_FILE_EMPTY`, `IMPORT_FILE_NOT_UTF8`, `IMPORT_FILE_MALFORMED`, `IMPORT_UNKNOWN_COLUMN`, `IMPORT_DUPLICATE_COLUMN`, `IMPORT_MISSING_COLUMN`, `IMPORT_TOO_MANY_ROWS` (400) or `IMPORT_FILE_TOO_LARGE` (413).
         */
        post: operations["importGames"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rooms, ordered by name */
        get: operations["list_1"];
        put?: never;
        /** Create a room */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/logo-fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download the image of a URL, to use it as the logo of a room
         * @description Returns the image itself (PNG, JPEG or WebP, up to 5 MB). A browser cannot read images of other sites, so it asks for them here, resizes the result and uploads it with `PUT /rooms/{id}/logo`; nothing is stored by this request. Only `http` and `https` URLs of public addresses. Fails with `LOGO_URL_INVALID` (400), `LOGO_URL_NOT_PUBLIC` (400), `LOGO_URL_UNREACHABLE` (502), `LOGO_TOO_LARGE` (413) or `LOGO_UNSUPPORTED_TYPE` (415).
         */
        post: operations["fetchLogo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a room */
        get: operations["get"];
        /**
         * Update a room
         * @description The currency can only change while the room has no games. Omit `active` to keep it.
         */
        put: operations["update_1"];
        post?: never;
        /**
         * Delete a room
         * @description Only rooms without games; otherwise deactivate it.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the logo of a room
         * @description The image, with a strong `ETag` (`If-None-Match` is answered with 304). Request it as `?v=<logoVersion of the room>`: that URL never changes its content, so it is served to be cached for a year without revalidation. Without `v`, or with another value, it is revalidated on every use.
         */
        get: operations["getLogo"];
        /**
         * Set the logo of a room
         * @description The body is the image itself: PNG, JPEG or WebP, up to 256 kB. The format is detected from the content and the declared `Content-Type` is ignored. Replaces the logo the room had and returns the room with its new `logoVersion`. Fails with `LOGO_EMPTY` (400), `LOGO_TOO_LARGE` (413) or `LOGO_UNSUPPORTED_TYPE` (415).
         */
        put: operations["replaceLogo"];
        post?: never;
        /** Delete the logo of a room */
        delete: operations["deleteLogo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results of the finished games per group, for each currency
         * @description Groups by period (day, week, month, year), game type, variant, room, modality, buy-in or range of buy-ins, name of the game or day of the week, with the same figures as the summary. Ranges of buy-ins are fixed: free, below 1, and from 1, 2, 5, 10, 20 and 50. Names are grouped ignoring case and surrounding spaces. Takes the filters of the games list, so e.g. `groupBy=MONTH&gameType=TOURNAMENT` gives the tournaments per month. Periods without games are not returned.
         */
        get: operations["groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results overall and per game type, for each currency
         * @description Takes the filters of the games list, all optional and combined with AND. Only finished games count in the figures; games in play are reported apart.
         */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List variants
         * @description Ordered by game type, built-in variants first, then user-defined ones by name.
         */
        get: operations["list"];
        put?: never;
        /** Create a user-defined variant */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a variant
         * @description Built-in variants can only be activated or deactivated; user-defined ones can also be renamed.
         */
        put: operations["update"];
        post?: never;
        /**
         * Delete a user-defined variant
         * @description Only when no game uses it; otherwise deactivate it.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BackupContents: {
            empty: boolean;
            /**
             * Format: date
             * @description Date of the first game
             */
            from?: string | null;
            /** Format: int32 */
            games: number;
            /** Format: int32 */
            gamesInPlay: number;
            /** Format: int32 */
            movements: number;
            /** Format: int32 */
            rooms: number;
            /**
             * Format: date
             * @description Date of the last game
             */
            to?: string | null;
            /** Format: int32 */
            variants: number;
        };
        BackupError: {
            code: string;
            message: string;
            path: string;
        };
        BackupRestoreResponse: {
            /** @description Version of the application that made the file */
            appVersion?: string | null;
            /** @description What the installation held before the restore: it is deleted by it (in a dry run or with errors, what it holds and would lose) */
            current: components["schemas"]["BackupContents"];
            /** @description The file was only checked: nothing was changed */
            dryRun: boolean;
            /**
             * Format: int32
             * @description Errors found in the content of the file; `errors` lists only the first ones
             */
            errorCount: number;
            errors: components["schemas"]["BackupError"][];
            /**
             * Format: date-time
             * @description When the file was made
             */
            exportedAt?: string | null;
            /** @description What the file holds */
            file: components["schemas"]["BackupContents"];
            /**
             * Format: int32
             * @description Version of the format of the file
             */
            formatVersion: number;
            /** @description The installation now holds what the file holds: not a dry run, and no errors */
            restored: boolean;
        };
        BankrollEvolutionResponse: {
            currencies: components["schemas"]["CurrencyEvolution"][];
            /** @enum {string} */
            groupBy: "DAY" | "WEEK" | "MONTH" | "YEAR";
        };
        BankrollFigures: {
            /** @description Sum of the adjustments, positive or negative */
            adjustments: number;
            /** @description deposited - withdrawn + adjustments + result */
            bankroll: number;
            bonuses: number;
            deposited: number;
            /**
             * Format: int64
             * @description Games without a result yet; informative
             */
            gamesInPlay: number;
            /** @description Net of the games, those in play included (their buy-in is already spent) */
            gamesNet: number;
            /** @description Money paid for the entries of the games in play; already subtracted in gamesNet */
            investedInPlay: number;
            /** @description Won or lost playing: gamesNet + bonuses */
            result: number;
            /** @description Value of the tickets won; informative, not part of the bankroll */
            ticketsWon: number;
            withdrawn: number;
        };
        BankrollSummaryResponse: {
            currencies: components["schemas"]["CurrencyBankroll"][];
        };
        BuyInRange: {
            from: number;
            /** @description Null for the last range, which has no upper end */
            to?: number | null;
        };
        Catalog: {
            currencies: components["schemas"]["CurrencyResponse"][];
            gameTypes: ("TOURNAMENT" | "SIT_AND_GO" | "CASH")[];
            modalities: ("NLHE" | "PLO")[];
        };
        CurrencyBankroll: {
            currencyCode: string;
            /** @description Rooms that are active or have games or movements, by name */
            rooms: components["schemas"]["RoomBankroll"][];
            /** @description The rooms in this currency plus the movements without a room */
            total: components["schemas"]["BankrollFigures"];
            /** @description Movements that belong to no room; they only count in the total */
            withoutRoom: components["schemas"]["BankrollFigures"];
        };
        CurrencyEvolution: {
            currencyCode: string;
            /** @description Rooms with movements or games in the range, or with a bankroll at its start, by name */
            rooms: components["schemas"]["RoomEvolution"][];
            /** @description The rooms of the response in this currency plus, without a room filter, the movements that belong to no room */
            total: components["schemas"]["EvolutionSeries"];
        };
        CurrencyGroups: {
            currencyCode: string;
            /** @description Groups with finished games. Periods from oldest to newest, buy-ins and their ranges from lowest to highest, days of the week from Monday, anything else from most to fewest games (games without a name last) */
            groups: components["schemas"]["Group"][];
        };
        CurrencyResponse: {
            code: string;
            /** Format: int32 */
            decimals: number;
            symbol: string;
        };
        CurrencySummary: {
            /** @description The game types with finished games, in catalog order */
            byGameType: components["schemas"]["GameTypeSummary"][];
            currencyCode: string;
            inPlay: components["schemas"]["InPlay"];
            /** @description Every finished game in this currency */
            total: components["schemas"]["StatsFigures"];
        };
        EvolutionPeriod: {
            /** @description Sum of the adjustments, positive or negative */
            adjustments: number;
            /** @description Bankroll at the end of the period: the starting bankroll plus deposited - withdrawn + adjustments + bonuses + gamesNet of this period and the earlier ones */
            bankroll: number;
            bonuses: number;
            deposited: number;
            /**
             * Format: date
             * @description Last day of the period, which may be after `to`
             */
            endsOn: string;
            /** @description Net of the games, those in play included (their buy-in is already spent) */
            gamesNet: number;
            /** @description DAY: 2026-01-19; WEEK: its Monday, 2026-01-19; MONTH: 2026-01; YEAR: 2026 */
            period: string;
            /**
             * Format: date
             * @description First day of the period, which may be before `from`
             */
            startsOn: string;
            withdrawn: number;
        };
        EvolutionSeries: {
            /** @description Periods with movements or games, oldest first */
            periods: components["schemas"]["EvolutionPeriod"][];
            /** @description Bankroll before the first day of the range (`from`): everything earlier counts. Zero without `from` */
            startingBankroll: number;
        };
        FinishGameRequest: {
            /** @description Bounties won. Not for cash games. Defaults to 0 */
            bounty?: number | null;
            /** @description Cash won, bounties apart. Cash game: amount when leaving the table. Defaults to 0 */
            prize?: number | null;
            ticketDescription?: string | null;
            /** @description Value of a tournament ticket won. Not for cash games. Defaults to 0 */
            ticketPrizeValue?: number | null;
        };
        GameImportResponse: {
            /** @description The file was only checked: nothing was stored */
            dryRun: boolean;
            /**
             * Format: int32
             * @description Errors found in the rows; `errors` lists only the first ones
             */
            errorCount: number;
            errors: components["schemas"]["ImportRowError"][];
            /**
             * Format: date
             * @description Date of the first game
             */
            from?: string | null;
            /**
             * Format: int32
             * @description Rows without errors
             */
            games: number;
            gamesByType: components["schemas"]["ImportGameTypeCount"][];
            /** @description The games were stored: not a dry run, and no row had errors */
            imported: boolean;
            /** @description Rooms that did not exist and are created by the import */
            newRooms: components["schemas"]["ImportedRoom"][];
            /** @description Variants that did not exist and are created by the import */
            newVariants: components["schemas"]["ImportedVariant"][];
            /**
             * Format: int32
             * @description Rows of the file with something in them, the header apart
             */
            rows: number;
            /**
             * Format: date
             * @description Date of the last game
             */
            to?: string | null;
            /** @description Games and their net per currency, to compare with the source of the file */
            totals: components["schemas"]["ImportCurrencyTotal"][];
        };
        GameNameResponse: {
            buyIn: number;
            /** @description Currency of the buy-in: the one of the room of that game */
            currencyCode: string;
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            /**
             * Format: int64
             * @description How many games have that name
             */
            games: number;
            /** @enum {string} */
            modality: "NLHE" | "PLO";
            /** @description As it was written in the most recent game of that name; names that differ only in case or surrounding spaces are the same one */
            name: string;
            variant?: components["schemas"]["VariantRef"] | null;
        };
        GameRequest: {
            /** @description Bounties won. Defaults to 0 */
            bounty?: number | null;
            /** @description Price of one entry, also when it was paid with a ticket. Cash game: amount brought to the table */
            buyIn: number;
            /**
             * Format: int32
             * @description Entries including re-entries. Defaults to 1
             */
            entries?: number | null;
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            /**
             * @description Defaults to NLHE
             * @enum {string|null}
             */
            modality?: "NLHE" | "PLO" | null;
            name?: string | null;
            notes?: string | null;
            /** @description One entry was paid with a ticket instead of cash. Defaults to false */
            paidWithTicket?: boolean | null;
            /**
             * @description Optional local start time (HH:mm), to order the games of a day
             * @example 21:30
             */
            playedAt?: string | null;
            /** Format: date */
            playedOn: string;
            /** @description Cash won, bounties apart. Cash game: amount when leaving the table. Defaults to 0 */
            prize?: number | null;
            /** Format: int64 */
            roomId: number;
            /**
             * @description IN_PLAY (registered when it starts, no result yet) or FINISHED. When omitted: FINISHED if a result is sent (prize, bounty or ticket); otherwise IN_PLAY for a new game and unchanged for an existing one
             * @enum {string|null}
             */
            status?: "IN_PLAY" | "FINISHED" | null;
            ticketDescription?: string | null;
            /** @description Value of a tournament ticket won as a prize; informative, not part of net. Defaults to 0 */
            ticketPrizeValue?: number | null;
            /**
             * Format: int64
             * @description Optional; must be a variant of the game type
             */
            variantId?: number | null;
        };
        GameResponse: {
            bounty: number;
            buyIn: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Currency of every amount of this game (the one of its room) */
            currencyCode: string;
            /** Format: int32 */
            entries: number;
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            /** Format: int64 */
            id: number;
            /** @description Money paid for the entries (an entry paid with a ticket costs nothing) */
            invested: number;
            /** @enum {string} */
            modality: "NLHE" | "PLO";
            name?: string | null;
            /** @description Real money won or lost: won - invested */
            net: number;
            notes?: string | null;
            paidWithTicket: boolean;
            /** @example 21:30:00 */
            playedAt?: string | null;
            /** Format: date */
            playedOn: string;
            prize: number;
            room: components["schemas"]["RoomRef"];
            /**
             * @description IN_PLAY while the result is not known yet; its buy-in already counts in net
             * @enum {string}
             */
            status: "IN_PLAY" | "FINISHED";
            ticketDescription?: string | null;
            ticketPrizeValue: number;
            /** Format: date-time */
            updatedAt: string;
            variant?: components["schemas"]["VariantRef"] | null;
            /** @description Money won: prize + bounty */
            won: number;
        };
        GameTypeSummary: {
            figures: components["schemas"]["StatsFigures"];
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
        };
        Group: {
            /** @description The group broken down by game type (those with games, in catalog order); only when asked for with `byGameType=true` */
            byGameType?: components["schemas"]["GameTypeSummary"][] | null;
            /** @description Net of this period and the earlier ones in the response, so it starts from zero at the beginning of the filtered range; only for groups in time */
            cumulativeNet?: number | null;
            figures: components["schemas"]["StatsFigures"];
            key: components["schemas"]["GroupKey"];
        };
        GroupKey: {
            /** @description BUY_IN */
            buyIn?: number | null;
            /** @description BUY_IN_RANGE */
            buyInRange?: components["schemas"]["BuyInRange"] | null;
            /**
             * @description GAME_TYPE, and VARIANT (the type the variant belongs to)
             * @enum {string|null}
             */
            gameType?: "TOURNAMENT" | "SIT_AND_GO" | "CASH" | null;
            /**
             * @description MODALITY
             * @enum {string|null}
             */
            modality?: "NLHE" | "PLO" | null;
            /** @description NAME, as written in most of its games; null for the games without a name */
            name?: string | null;
            /** @description DAY: 2026-01-19; WEEK: its Monday, 2026-01-19; MONTH: 2026-01; YEAR: 2026 */
            period?: string | null;
            /** @description ROOM */
            room?: components["schemas"]["RoomRef"] | null;
            /** @description VARIANT; null for the games of the type without a variant */
            variant?: components["schemas"]["VariantRef"] | null;
            /**
             * Format: int32
             * @description WEEKDAY: 1 (Monday) to 7 (Sunday)
             */
            weekday?: number | null;
        };
        ImportCurrencyTotal: {
            currencyCode: string;
            /** Format: int32 */
            games: number;
            net: number;
        };
        ImportGameTypeCount: {
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            /** Format: int32 */
            games: number;
        };
        ImportRowError: {
            code: string;
            field?: string | null;
            message: string;
            /** Format: int32 */
            row: number;
        };
        ImportedRoom: {
            currencyCode: string;
            name: string;
        };
        ImportedVariant: {
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            name: string;
        };
        InPlay: {
            /** Format: int64 */
            games: number;
            /** @description Money paid so far for their entries */
            invested: number;
        };
        LogoFetchRequest: {
            url: string;
        };
        MovementRequest: {
            /** @description Greater than zero: the type gives the direction (a withdrawal subtracts). Only an ADJUSTMENT can be negative */
            amount: number;
            /** @description Only for a movement without a room, e.g. EUR */
            currencyCode?: string | null;
            notes?: string | null;
            /** Format: date */
            occurredOn: string;
            /**
             * Format: int64
             * @description Room the movement belongs to; the amount is in its currency. Omit it, and give a currency, for a movement of the bankroll as a whole
             */
            roomId?: number | null;
            /** @enum {string} */
            type: "DEPOSIT" | "WITHDRAWAL" | "BONUS" | "ADJUSTMENT";
        };
        MovementResponse: {
            amount: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Currency of the amount: the one of the room, or its own without a room */
            currencyCode: string;
            /** Format: int64 */
            id: number;
            notes?: string | null;
            /** Format: date */
            occurredOn: string;
            /** @description Null for a movement of the bankroll as a whole */
            room?: components["schemas"]["RoomRef"] | null;
            /** @description Effect on the bankroll: the amount, negative for a withdrawal */
            signedAmount: number;
            /** @enum {string} */
            type: "DEPOSIT" | "WITHDRAWAL" | "BONUS" | "ADJUSTMENT";
            /** Format: date-time */
            updatedAt: string;
        };
        PageResponseGameResponse: {
            items: components["schemas"]["GameResponse"][];
            /**
             * Format: int32
             * @description Zero-based page number
             */
            page: number;
            /**
             * Format: int32
             * @description Requested page size
             */
            size: number;
            /** Format: int64 */
            totalItems: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseMovementResponse: {
            items: components["schemas"]["MovementResponse"][];
            /**
             * Format: int32
             * @description Zero-based page number
             */
            page: number;
            /**
             * Format: int32
             * @description Requested page size
             */
            size: number;
            /** Format: int64 */
            totalItems: number;
            /** Format: int32 */
            totalPages: number;
        };
        RebuyRequest: {
            /** @description Amount added to the buy-in of the game */
            amount: number;
        };
        RoomBankroll: {
            active: boolean;
            figures: components["schemas"]["BankrollFigures"];
            room: components["schemas"]["RoomRef"];
        };
        RoomEvolution: {
            active: boolean;
            room: components["schemas"]["RoomRef"];
            series: components["schemas"]["EvolutionSeries"];
        };
        RoomRef: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        RoomRequest: {
            /** @description Inactive rooms keep their history but are not offered for new games. Defaults to true. */
            active?: boolean | null;
            /**
             * @description ISO 4217 code of one of the currencies of the catalog
             * @example EUR
             */
            currencyCode: string;
            name: string;
        };
        RoomResponse: {
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            currencyCode: string;
            /** Format: int64 */
            id: number;
            /** @description The room has games or bankroll movements: it cannot be deleted and its currency cannot change */
            inUse: boolean;
            /** @description Null when the room has no logo. Otherwise an opaque value that changes every time the logo is uploaded: get the image from `/rooms/{id}/logo?v=<logoVersion>` */
            logoVersion?: string | null;
            name: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StatsFigures: {
            /** @description Mean buy-in of a game; cash games apart */
            averageBuyIn?: number | null;
            /** @description Bounties, already included in won */
            bounties: number;
            /**
             * Format: int64
             * @description Entries, re-entries included
             */
            entries: number;
            /**
             * Format: int64
             * @description Games played
             */
            games: number;
            /**
             * Format: int64
             * @description Games with a prize or a ticket won (bounties do not count); cash games apart
             */
            gamesInTheMoney?: number | null;
            /**
             * Format: int64
             * @description Games with a prize, a bounty or a ticket won; cash games apart
             */
            gamesWithPrize?: number | null;
            /** @description gamesInTheMoney / games, cash games apart */
            inTheMoneyRate?: number | null;
            /** @description Money paid for the entries (an entry paid with a ticket costs nothing) */
            invested: number;
            /** @description won - invested */
            net: number;
            /** @description net / invested; null when nothing was invested */
            roi?: number | null;
            /** @description Value of the tickets won; informative, not part of won, net or roi */
            ticketsWon: number;
            /**
             * Format: int64
             * @description Games with a positive net
             */
            winningGames: number;
            /** @description winningGames / games */
            winningRate?: number | null;
            /** @description gamesWithPrize / games, cash games apart */
            withPrizeRate?: number | null;
            /** @description Money won: prizes + bounties */
            won: number;
        };
        StatsGroupsResponse: {
            currencies: components["schemas"]["CurrencyGroups"][];
            /** @enum {string} */
            groupBy: "DAY" | "WEEK" | "MONTH" | "YEAR" | "GAME_TYPE" | "VARIANT" | "ROOM" | "MODALITY" | "BUY_IN" | "BUY_IN_RANGE" | "NAME" | "WEEKDAY";
        };
        StatsSummaryResponse: {
            currencies: components["schemas"]["CurrencySummary"][];
        };
        VariantCreateRequest: {
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            name: string;
        };
        VariantRef: {
            code?: string | null;
            /** Format: int64 */
            id: number;
            name?: string | null;
        };
        VariantResponse: {
            active: boolean;
            builtIn: boolean;
            /** @description Code of a built-in variant, translated by the client; null for user-defined ones */
            code?: string | null;
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            /** Format: int64 */
            id: number;
            /** @description The variant is used by games: it cannot be deleted */
            inUse: boolean;
            /** @description Name of a user-defined variant; null for built-in ones */
            name?: string | null;
        };
        VariantUpdateRequest: {
            /** @description Inactive variants keep their history but are not offered for new games */
            active: boolean;
            /** @description New name of a user-defined variant. Must be omitted (or null) for built-in variants. */
            name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    downloadBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    restoreBackup: {
        parameters: {
            query?: {
                /** @description Only check the file and report what it holds and what would be deleted */
                dryRun?: boolean;
                /** @description Delete what the installation holds; needed unless it is empty */
                replace?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupRestoreResponse"];
                };
            };
        };
    };
    evolution: {
        parameters: {
            query: {
                /** @description Length of the periods; weeks start on Monday */
                groupBy: "DAY" | "WEEK" | "MONTH" | "YEAR";
                /** @description First day of the range: what happened before is the starting bankroll */
                from?: string;
                /** @description Last day of the range: what happened after it does not count */
                to?: string;
                /** @description One or more rooms: only they count, without the movements that belong to no room */
                roomId?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankrollEvolutionResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                /** @description On or after this date */
                from?: string;
                /** @description On or before this date */
                to?: string;
                type?: "DEPOSIT" | "WITHDRAWAL" | "BONUS" | "ADJUSTMENT";
                /** @description One or more rooms: movements of any of them */
                roomId?: number[];
                /** @description true: only movements that belong to no room; false: only those of a room */
                withoutRoom?: boolean;
                /** @description Currency of the amount, e.g. EUR */
                currency?: string;
                /** @description Zero-based page number */
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseMovementResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    summary_1: {
        parameters: {
            query?: {
                /** @description Only movements and games on or after this date: with dates, the figures are those of the period (what the bankroll changed, what was won or lost) */
                from?: string;
                /** @description Only movements and games on or before this date */
                to?: string;
                /** @description One or more rooms: only they are listed and added up, without the movements that belong to no room */
                roomId?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankrollSummaryResponse"];
                };
            };
        };
    };
    catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    exportGames: {
        parameters: {
            query: {
                format: "CSV" | "XLSX";
                /** @description Played on or after this date */
                from?: string;
                /** @description Played on or before this date */
                to?: string;
                /** @description One or more game types: games of any of them */
                gameType?: ("TOURNAMENT" | "SIT_AND_GO" | "CASH")[];
                modality?: "NLHE" | "PLO";
                /** @description One or more rooms: games in any of them */
                roomId?: number[];
                /** @description One or more variants: games of any of them */
                variantId?: number[];
                /** @description Currency of the room, e.g. EUR */
                currency?: string;
                /** @description Text contained in the name or the notes, ignoring case */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    "text/csv": string;
                };
            };
        };
    };
    exportMovements: {
        parameters: {
            query: {
                format: "CSV" | "XLSX";
                /** @description On or after this date */
                from?: string;
                /** @description On or before this date */
                to?: string;
                type?: "DEPOSIT" | "WITHDRAWAL" | "BONUS" | "ADJUSTMENT";
                /** @description One or more rooms: movements of any of them */
                roomId?: number[];
                /** @description true: only movements that belong to no room; false: only those of a room */
                withoutRoom?: boolean;
                /** @description Currency of the amount, e.g. EUR */
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    "text/csv": string;
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                /** @description Played on or after this date */
                from?: string;
                /** @description Played on or before this date */
                to?: string;
                /** @description One or more game types: games of any of them */
                gameType?: ("TOURNAMENT" | "SIT_AND_GO" | "CASH")[];
                modality?: "NLHE" | "PLO";
                /** @description One or more rooms: games in any of them */
                roomId?: number[];
                /** @description One or more variants: games of any of them */
                variantId?: number[];
                status?: "IN_PLAY" | "FINISHED";
                /** @description Currency of the room, e.g. EUR */
                currency?: string;
                /** @description Text contained in the name or the notes, ignoring case */
                q?: string;
                /** @description Zero-based page number */
                page?: number;
                size?: number;
                /** @description `<field>,<asc|desc>` with field one of playedOn, net, buyIn, prize, won, createdAt */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseGameResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    names: {
        parameters: {
            query?: {
                /** @description Text contained in the name, ignoring case and searched literally; with less than 2 characters, surrounding spaces apart, nothing is suggested */
                q?: string;
                /** @description Only the games of this type: their names, counts and figures */
                gameType?: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameNameResponse"][];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FinishGameRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    addReEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    addRebuy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RebuyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    importGames: {
        parameters: {
            query?: {
                /** @description Only check the file and report what it would import */
                dryRun?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameImportResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    fetchLogo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoFetchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLogo: {
        parameters: {
            query?: {
                /** @description The `logoVersion` of the room */
                v?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replaceLogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
                "image/webp": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    deleteLogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    groups: {
        parameters: {
            query: {
                groupBy: "DAY" | "WEEK" | "MONTH" | "YEAR" | "GAME_TYPE" | "VARIANT" | "ROOM" | "MODALITY" | "BUY_IN" | "BUY_IN_RANGE" | "NAME" | "WEEKDAY";
                /** @description Also break each group down by game type */
                byGameType?: boolean;
                /** @description Played on or after this date */
                from?: string;
                /** @description Played on or before this date */
                to?: string;
                /** @description One or more game types: games of any of them */
                gameType?: ("TOURNAMENT" | "SIT_AND_GO" | "CASH")[];
                modality?: "NLHE" | "PLO";
                /** @description One or more rooms: games in any of them */
                roomId?: number[];
                /** @description One or more variants: games of any of them */
                variantId?: number[];
                /** @description Currency of the room, e.g. EUR */
                currency?: string;
                /** @description Text contained in the name or the notes, ignoring case */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsGroupsResponse"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: {
                /** @description Played on or after this date */
                from?: string;
                /** @description Played on or before this date */
                to?: string;
                /** @description One or more game types: games of any of them */
                gameType?: ("TOURNAMENT" | "SIT_AND_GO" | "CASH")[];
                modality?: "NLHE" | "PLO";
                /** @description One or more rooms: games in any of them */
                roomId?: number[];
                /** @description One or more variants: games of any of them */
                variantId?: number[];
                /** @description Currency of the room, e.g. EUR */
                currency?: string;
                /** @description Text contained in the name or the notes, ignoring case */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummaryResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                gameType?: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
