/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bankroll/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bankroll movements, newest first
         * @description All filters are optional and combined with AND.
         */
        get: operations["list_3"];
        put?: never;
        /**
         * Record a bankroll movement
         * @description Of a room (`roomId`), or of the bankroll as a whole (`currencyCode`, no room).
         */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankroll/movements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a bankroll movement */
        get: operations["get_2"];
        /**
         * Update a bankroll movement
         * @description Replaces every field.
         */
        put: operations["update_3"];
        post?: never;
        /** Delete a bankroll movement */
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankroll/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poker bankroll per currency and room
         * @description bankroll = deposited - withdrawn + adjustments + result, with result = net of the games + bonuses. It is not the balance of the room account: with no movements recorded it is just the result, negative when losing.
         */
        get: operations["summary_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Currencies, game types and modalities, in display order */
        get: operations["catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List games
         * @description All filters are optional and combined with AND.
         */
        get: operations["list_2"];
        put?: never;
        /**
         * Record a game
         * @description With only the required fields the game is recorded as in play; send a result (or `status: FINISHED`) to record it finished.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game */
        get: operations["get_1"];
        /**
         * Update a game
         * @description Replaces every field; omitted optional fields take their default.
         */
        put: operations["update_2"];
        post?: never;
        /** Delete a game */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish a game in play
         * @description Sets its result; with no body (or an empty one) nothing was won.
         */
        post: operations["finish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/re-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a re-entry to a tournament or Sit&Go in play
         * @description Adds one entry, paid in cash.
         */
        post: operations["addReEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/rebuys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a rebuy to a cash game in play
         * @description Adds the amount to the buy-in.
         */
        post: operations["addRebuy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rooms, ordered by name */
        get: operations["list_1"];
        put?: never;
        /** Create a room */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a room */
        get: operations["get"];
        /**
         * Update a room
         * @description The currency can only change while the room has no games. Omit `active` to keep it.
         */
        put: operations["update_1"];
        post?: never;
        /**
         * Delete a room
         * @description Only rooms without games; otherwise deactivate it.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results of the finished games per group, for each currency
         * @description Groups by period (day, week, month, year), game type, variant, room, modality or buy-in, with the same figures as the summary. Takes the filters of the games list, so e.g. `groupBy=MONTH&gameType=TOURNAMENT` gives the tournaments per month. Periods without games are not returned.
         */
        get: operations["groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results overall and per game type, for each currency
         * @description Takes the filters of the games list, all optional and combined with AND. Only finished games count in the figures; games in play are reported apart.
         */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List variants
         * @description Ordered by game type, built-in variants first, then user-defined ones by name.
         */
        get: operations["list"];
        put?: never;
        /** Create a user-defined variant */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/variants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a variant
         * @description Built-in variants can only be activated or deactivated; user-defined ones can also be renamed.
         */
        put: operations["update"];
        post?: never;
        /**
         * Delete a user-defined variant
         * @description Only when no game uses it; otherwise deactivate it.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BankrollFigures: {
            /** @description Sum of the adjustments, positive or negative */
            adjustments: number;
            /** @description deposited - withdrawn + adjustments + result */
            bankroll: number;
            bonuses: number;
            deposited: number;
            /**
             * Format: int64
             * @description Games without a result yet; informative
             */
            gamesInPlay: number;
            /** @description Net of the games, those in play included (their buy-in is already spent) */
            gamesNet: number;
            /** @description Money paid for the entries of the games in play; already subtracted in gamesNet */
            investedInPlay: number;
            /** @description Won or lost playing: gamesNet + bonuses */
            result: number;
            /** @description Value of the tickets won; informative, not part of the bankroll */
            ticketsWon: number;
            withdrawn: number;
        };
        BankrollSummaryResponse: {
            currencies: components["schemas"]["CurrencyBankroll"][];
        };
        Catalog: {
            currencies: components["schemas"]["CurrencyResponse"][];
            gameTypes: ("TOURNAMENT" | "SIT_AND_GO" | "CASH")[];
            modalities: ("NLHE" | "PLO")[];
        };
        CurrencyBankroll: {
            currencyCode: string;
            /** @description Rooms that are active or have games or movements, by name */
            rooms: components["schemas"]["RoomBankroll"][];
            /** @description The rooms in this currency plus the movements without a room */
            total: components["schemas"]["BankrollFigures"];
            /** @description Movements that belong to no room; they only count in the total */
            withoutRoom: components["schemas"]["BankrollFigures"];
        };
        CurrencyGroups: {
            currencyCode: string;
            /** @description Groups with finished games. Periods from oldest to newest, buy-ins from lowest to highest, anything else from most to fewest games */
            groups: components["schemas"]["Group"][];
        };
        CurrencyResponse: {
            code: string;
            /** Format: int32 */
            decimals: number;
            symbol: string;
        };
        CurrencySummary: {
            /** @description The game types with finished games, in catalog order */
            byGameType: components["schemas"]["GameTypeSummary"][];
            currencyCode: string;
            inPlay: components["schemas"]["InPlay"];
            /** @description Every finished game in this currency */
            total: components["schemas"]["StatsFigures"];
        };
        FinishGameRequest: {
            /** @description Bounties won. Not for cash games. Defaults to 0 */
            bounty?: number | null;
            /** @description Cash won, bounties apart. Cash game: amount when leaving the table. Defaults to 0 */
            prize?: number | null;
            ticketDescription?: string | null;
            /** @description Value of a tournament ticket won. Not for cash games. Defaults to 0 */
            ticketPrizeValue?: number | null;
        };
        GameRequest: {
            /** @description Bounties won. Defaults to 0 */
            bounty?: number | null;
            /** @description Price of one entry, also when it was paid with a ticket. Cash game: amount brought to the table */
            buyIn: number;
            /**
             * Format: int32
             * @description Entries including re-entries. Defaults to 1
             */
            entries?: number | null;
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            /**
             * @description Defaults to NLHE
             * @enum {string|null}
             */
            modality?: "NLHE" | "PLO" | null;
            name?: string | null;
            notes?: string | null;
            /** @description One entry was paid with a ticket instead of cash. Defaults to false */
            paidWithTicket?: boolean | null;
            /**
             * @description Optional local start time (HH:mm), to order the games of a day
             * @example 21:30
             */
            playedAt?: string | null;
            /** Format: date */
            playedOn: string;
            /** @description Cash won, bounties apart. Cash game: amount when leaving the table. Defaults to 0 */
            prize?: number | null;
            /** Format: int64 */
            roomId: number;
            /**
             * @description IN_PLAY (registered when it starts, no result yet) or FINISHED. When omitted: FINISHED if a result is sent (prize, bounty or ticket); otherwise IN_PLAY for a new game and unchanged for an existing one
             * @enum {string|null}
             */
            status?: "IN_PLAY" | "FINISHED" | null;
            ticketDescription?: string | null;
            /** @description Value of a tournament ticket won as a prize; informative, not part of net. Defaults to 0 */
            ticketPrizeValue?: number | null;
            /**
             * Format: int64
             * @description Optional; must be a variant of the game type
             */
            variantId?: number | null;
        };
        GameResponse: {
            bounty: number;
            buyIn: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Currency of every amount of this game (the one of its room) */
            currencyCode: string;
            /** Format: int32 */
            entries: number;
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            /** Format: int64 */
            id: number;
            /** @description Money paid for the entries (an entry paid with a ticket costs nothing) */
            invested: number;
            /** @enum {string} */
            modality: "NLHE" | "PLO";
            name?: string | null;
            /** @description Real money won or lost: won - invested */
            net: number;
            notes?: string | null;
            paidWithTicket: boolean;
            /** @example 21:30:00 */
            playedAt?: string | null;
            /** Format: date */
            playedOn: string;
            prize: number;
            room: components["schemas"]["RoomRef"];
            /**
             * @description IN_PLAY while the result is not known yet; its buy-in already counts in net
             * @enum {string}
             */
            status: "IN_PLAY" | "FINISHED";
            ticketDescription?: string | null;
            ticketPrizeValue: number;
            /** Format: date-time */
            updatedAt: string;
            variant?: components["schemas"]["VariantRef"] | null;
            /** @description Money won: prize + bounty */
            won: number;
        };
        GameTypeSummary: {
            figures: components["schemas"]["StatsFigures"];
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
        };
        Group: {
            /** @description Net of this period and the earlier ones in the response, so it starts from zero at the beginning of the filtered range; only for groups in time */
            cumulativeNet?: number | null;
            figures: components["schemas"]["StatsFigures"];
            key: components["schemas"]["GroupKey"];
        };
        GroupKey: {
            /** @description BUY_IN */
            buyIn?: number | null;
            /**
             * @description GAME_TYPE, and VARIANT (the type the variant belongs to)
             * @enum {string|null}
             */
            gameType?: "TOURNAMENT" | "SIT_AND_GO" | "CASH" | null;
            /**
             * @description MODALITY
             * @enum {string|null}
             */
            modality?: "NLHE" | "PLO" | null;
            /** @description DAY: 2026-01-19; WEEK: its Monday, 2026-01-19; MONTH: 2026-01; YEAR: 2026 */
            period?: string | null;
            /** @description ROOM */
            room?: components["schemas"]["RoomRef"] | null;
            /** @description VARIANT; null for the games of the type without a variant */
            variant?: components["schemas"]["VariantRef"] | null;
        };
        InPlay: {
            /** Format: int64 */
            games: number;
            /** @description Money paid so far for their entries */
            invested: number;
        };
        MovementRequest: {
            /** @description Greater than zero: the type gives the direction (a withdrawal subtracts). Only an ADJUSTMENT can be negative */
            amount: number;
            /** @description Only for a movement without a room, e.g. EUR */
            currencyCode?: string | null;
            notes?: string | null;
            /** Format: date */
            occurredOn: string;
            /**
             * Format: int64
             * @description Room the movement belongs to; the amount is in its currency. Omit it, and give a currency, for a movement of the bankroll as a whole
             */
            roomId?: number | null;
            /** @enum {string} */
            type: "DEPOSIT" | "WITHDRAWAL" | "BONUS" | "ADJUSTMENT";
        };
        MovementResponse: {
            amount: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Currency of the amount: the one of the room, or its own without a room */
            currencyCode: string;
            /** Format: int64 */
            id: number;
            notes?: string | null;
            /** Format: date */
            occurredOn: string;
            /** @description Null for a movement of the bankroll as a whole */
            room?: components["schemas"]["RoomRef"] | null;
            /** @description Effect on the bankroll: the amount, negative for a withdrawal */
            signedAmount: number;
            /** @enum {string} */
            type: "DEPOSIT" | "WITHDRAWAL" | "BONUS" | "ADJUSTMENT";
            /** Format: date-time */
            updatedAt: string;
        };
        PageResponseGameResponse: {
            items: components["schemas"]["GameResponse"][];
            /**
             * Format: int32
             * @description Zero-based page number
             */
            page: number;
            /**
             * Format: int32
             * @description Requested page size
             */
            size: number;
            /** Format: int64 */
            totalItems: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseMovementResponse: {
            items: components["schemas"]["MovementResponse"][];
            /**
             * Format: int32
             * @description Zero-based page number
             */
            page: number;
            /**
             * Format: int32
             * @description Requested page size
             */
            size: number;
            /** Format: int64 */
            totalItems: number;
            /** Format: int32 */
            totalPages: number;
        };
        RebuyRequest: {
            /** @description Amount added to the buy-in of the game */
            amount: number;
        };
        RoomBankroll: {
            active: boolean;
            figures: components["schemas"]["BankrollFigures"];
            room: components["schemas"]["RoomRef"];
        };
        RoomRef: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        RoomRequest: {
            /** @description Inactive rooms keep their history but are not offered for new games. Defaults to true. */
            active?: boolean | null;
            /**
             * @description ISO 4217 code of one of the currencies of the catalog
             * @example EUR
             */
            currencyCode: string;
            name: string;
        };
        RoomResponse: {
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            currencyCode: string;
            /** Format: int64 */
            id: number;
            /** @description The room has games or bankroll movements: it cannot be deleted and its currency cannot change */
            inUse: boolean;
            name: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StatsFigures: {
            /** @description Mean buy-in of a game; cash games apart */
            averageBuyIn?: number | null;
            /** @description Bounties, already included in won */
            bounties: number;
            /**
             * Format: int64
             * @description Entries, re-entries included
             */
            entries: number;
            /**
             * Format: int64
             * @description Games played
             */
            games: number;
            /**
             * Format: int64
             * @description Games with a prize or a ticket won (bounties do not count); cash games apart
             */
            gamesInTheMoney?: number | null;
            /**
             * Format: int64
             * @description Games with a prize, a bounty or a ticket won; cash games apart
             */
            gamesWithPrize?: number | null;
            /** @description gamesInTheMoney / games, cash games apart */
            inTheMoneyRate?: number | null;
            /** @description Money paid for the entries (an entry paid with a ticket costs nothing) */
            invested: number;
            /** @description won - invested */
            net: number;
            /** @description net / invested; null when nothing was invested */
            roi?: number | null;
            /** @description Value of the tickets won; informative, not part of won, net or roi */
            ticketsWon: number;
            /**
             * Format: int64
             * @description Games with a positive net
             */
            winningGames: number;
            /** @description winningGames / games */
            winningRate?: number | null;
            /** @description gamesWithPrize / games, cash games apart */
            withPrizeRate?: number | null;
            /** @description Money won: prizes + bounties */
            won: number;
        };
        StatsGroupsResponse: {
            currencies: components["schemas"]["CurrencyGroups"][];
            /** @enum {string} */
            groupBy: "DAY" | "WEEK" | "MONTH" | "YEAR" | "GAME_TYPE" | "VARIANT" | "ROOM" | "MODALITY" | "BUY_IN";
        };
        StatsSummaryResponse: {
            currencies: components["schemas"]["CurrencySummary"][];
        };
        VariantCreateRequest: {
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            name: string;
        };
        VariantRef: {
            code?: string | null;
            /** Format: int64 */
            id: number;
            name?: string | null;
        };
        VariantResponse: {
            active: boolean;
            builtIn: boolean;
            /** @description Code of a built-in variant, translated by the client; null for user-defined ones */
            code?: string | null;
            /** @enum {string} */
            gameType: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
            /** Format: int64 */
            id: number;
            /** @description The variant is used by games: it cannot be deleted */
            inUse: boolean;
            /** @description Name of a user-defined variant; null for built-in ones */
            name?: string | null;
        };
        VariantUpdateRequest: {
            /** @description Inactive variants keep their history but are not offered for new games */
            active: boolean;
            /** @description New name of a user-defined variant. Must be omitted (or null) for built-in variants. */
            name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_3: {
        parameters: {
            query?: {
                /** @description On or after this date */
                from?: string;
                /** @description On or before this date */
                to?: string;
                type?: "DEPOSIT" | "WITHDRAWAL" | "BONUS" | "ADJUSTMENT";
                roomId?: number;
                /** @description true: only movements that belong to no room; false: only those of a room */
                withoutRoom?: boolean;
                /** @description Currency of the amount, e.g. EUR */
                currency?: string;
                /** @description Zero-based page number */
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseMovementResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    summary_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankrollSummaryResponse"];
                };
            };
        };
    };
    catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                /** @description Played on or after this date */
                from?: string;
                /** @description Played on or before this date */
                to?: string;
                gameType?: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
                modality?: "NLHE" | "PLO";
                roomId?: number;
                variantId?: number;
                status?: "IN_PLAY" | "FINISHED";
                /** @description Currency of the room, e.g. EUR */
                currency?: string;
                /** @description Text contained in the name or the notes, ignoring case */
                q?: string;
                /** @description Zero-based page number */
                page?: number;
                size?: number;
                /** @description `<field>,<asc|desc>` with field one of playedOn, net, buyIn, prize, createdAt */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseGameResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    finish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FinishGameRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    addReEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    addRebuy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RebuyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    groups: {
        parameters: {
            query: {
                groupBy: "DAY" | "WEEK" | "MONTH" | "YEAR" | "GAME_TYPE" | "VARIANT" | "ROOM" | "MODALITY" | "BUY_IN";
                /** @description Played on or after this date */
                from?: string;
                /** @description Played on or before this date */
                to?: string;
                gameType?: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
                modality?: "NLHE" | "PLO";
                roomId?: number;
                variantId?: number;
                /** @description Currency of the room, e.g. EUR */
                currency?: string;
                /** @description Text contained in the name or the notes, ignoring case */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsGroupsResponse"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: {
                /** @description Played on or after this date */
                from?: string;
                /** @description Played on or before this date */
                to?: string;
                gameType?: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
                modality?: "NLHE" | "PLO";
                roomId?: number;
                variantId?: number;
                /** @description Currency of the room, e.g. EUR */
                currency?: string;
                /** @description Text contained in the name or the notes, ignoring case */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummaryResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                gameType?: "TOURNAMENT" | "SIT_AND_GO" | "CASH";
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
